-- Bookshelf Supabase Production Database Schema
-- Run this in your Supabase SQL Editor (supabase.com -> SQL Editor -> New Query -> Run)

-- 1. BOOKS TABLE
create table if not exists public.books (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  title text not null,
  sub text,
  author text not null,
  cat text not null,
  type text default 'free',
  price numeric default 0,
  list numeric,
  rating numeric default 4.8,
  reviews integer default 250,
  pages integer default 100,
  badge text,
  bought text default 'Instant download',
  bg text default '#0f2a43',
  fg text default '#ffffff',
  ac text default '#f59e0b',
  pat text default 'p-rings',
  blurb text,
  feat jsonb default '[]'::jsonb,
  desc_html text,
  drive_url text,
  cover_image text,
  partner text,
  partner_url text,
  downloads integer default 0,
  created_at timestamptz default now()
);

-- 2. CATEGORIES TABLE
create table if not exists public.categories (
  id text primary key,
  name text not null,
  slug text not null,
  badge text,
  seo_title text,
  h1 text,
  intro text
);

-- 3. REVIEWS TABLE
create table if not exists public.reviews (
  id text primary key,
  book_id integer not null,
  title text not null,
  body text not null,
  author text not null,
  rating integer default 5,
  date text not null,
  verified boolean default true,
  helpful_count integer default 0,
  created_at timestamptz default now()
);

-- 4. SUBSCRIBERS TABLE
create table if not exists public.subscribers (
  id text primary key,
  email text unique not null,
  created_at timestamptz default now()
);

-- 5. SETTINGS TABLE
create table if not exists public.settings (
  id text primary key default 'global',
  passcode text,
  admin_email text,
  direct_smart_link text,
  banner_ad_code text,
  interstitial_ad_code text,
  ad_timer_seconds integer default 8,
  auto_redirect_enabled boolean default true,
  updated_at timestamptz default now()
);

-- Enable Row Level Security (RLS)
alter table public.books enable row level security;
alter table public.categories enable row level security;
alter table public.reviews enable row level security;
alter table public.subscribers enable row level security;
alter table public.settings enable row level security;

-- Policies for public and admin operations
drop policy if exists "Allow all access to books" on public.books;
create policy "Allow all access to books" on public.books for all using (true) with check (true);

drop policy if exists "Allow all access to categories" on public.categories;
create policy "Allow all access to categories" on public.categories for all using (true) with check (true);

drop policy if exists "Allow all access to reviews" on public.reviews;
create policy "Allow all access to reviews" on public.reviews for all using (true) with check (true);

drop policy if exists "Allow all access to subscribers" on public.subscribers;
create policy "Allow all access to subscribers" on public.subscribers for all using (true) with check (true);

drop policy if exists "Allow all access to settings" on public.settings;
create policy "Allow all access to settings" on public.settings for all using (true) with check (true);
